import {
  FileText,
  Settings,
  ShieldAlert,
  User2,
  Truck,
  Crown,
  Zap,
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Megaphone,
  Image,
  Shield,
  LifeBuoy,
  Sparkles,
  MessageSquare,
  Target,
  Star,
  LayoutGrid,
  BookOpen,
  Lock,
  BarChart,
  CheckCircle2,
  XCircle,
  SlidersHorizontal,
  Bell,
  CreditCard,
  User,
  Bike,
  Rocket,
  PackageCheck,
  PieChart,
  ClipboardList,
  Receipt,
  FileStack,
  Repeat,
  Box,
  Tags,
  Warehouse,
  Contact,
  Flag,
  Ticket,
  Gift,
  ScrollText,
  Undo2,
  UserCog,
  Plug,
  Settings2,
  Globe,
  Wallet,
  TrendingUp,
  TrendingDown,
  Barcode,
} from "lucide-react";
import { FeaturePermission } from "@/constants/feature-permission";

// Navigation organized by sections and workflow
// title: used for iconMap lookup; tKey: translation key for i18n
export const navSections = [
  // {
  //   id: 1.5,
  //   title: "Domain Find",
  //   tKey: "Domain Find",
  //   link: "/domain-finder",
  //   permission: FeaturePermission.CUSTOM_DOMAIN,
  //   icon: Globe,
  // },
  {
    id: "main",
    title: "General",
    tKey: "nav.main",
    icon: LayoutGrid,
    items: [
      {
        id: 1.6,
        title: "AI Daily Report",
        tKey: "nav.aiDailyReport",
        link: "/ai-report",
        permission: FeaturePermission.AI_REPORT,
        icon: Sparkles,
      },
      {
        id: 1.65,
        title: "Media",
        tKey: "nav.media",
        link: "/media",
        permission: FeaturePermission.MEDIA_MANAGEMENT,
        icon: Image,
      },
      {
        id: 1.7,
        title: "AI Live Feed",
        tKey: "nav.aiLiveFeed",
        link: "/ai-live-feed",
        permission: FeaturePermission.AI_LIVE_FEED,
        icon: MessageSquare,
      },
      {
        id: 1.8,
        title: "AI Sales Direction",
        tKey: "nav.aiSalesDirection",
        link: "/ai-sales-direction",
        permission: FeaturePermission.AI_SALES_DIRECTION,
        icon: Target,
      },
      {
        id: 1.9,
        title: "Statistics",
        tKey: "nav.statistics",
        link: "/statistics",
        permission: FeaturePermission.SUPERADMIN_STATISTICS,
        icon: Star,
      },
    ],
  },
  {
    id: "orders",
    title: "Order Management",
    tKey: "nav.orderManagement",
    icon: ShoppingCart,
    items: [
      {
        id: 6,
        title: "Order",
        tKey: "nav.order",
        link: "/orders",
        permission: FeaturePermission.ORDERS,
        icon: ClipboardList,
      },
      {
        id: 6.1,
        title: "Incomplete Orders",
        tKey: "nav.incompleteOrders",
        link: "/incomplete-orders",
        permission: FeaturePermission.INCOMPLETE_ORDERS,
        icon: XCircle,
      },
      {
        id: 7.0,
        title: "Credit Notes",
        tKey: "nav.creditNotes",
        link: "/credit-notes",
        permission: FeaturePermission.ORDERS,
        icon: Receipt,
      },
      {
        id: 7.5,
        title: "Courier",
        tKey: "nav.courier",
        icon: Truck,
        children: [
          {
            title: "Steadfast Courier",
            tKey: "nav.steadfastCourier",
            link: "/steadfast",
            permission: FeaturePermission.STEARDFAST,
            icon: PackageCheck,
          },
          {
            title: "Pathao Courier",
            tKey: "nav.pathaoCourier",
            link: "/pathao",
            permission: FeaturePermission.PATHAO,
            icon: Bike,
          },
          {
            title: "RedX Courier",
            tKey: "nav.redxCourier",
            link: "/redx",
            permission: FeaturePermission.REDX,
            icon: Rocket,
          },
        ],
      },
      {
        id: 7.8,
        title: "Fraud Checker",
        tKey: "nav.fraudChecker",
        link: "/fraud",
        permission: FeaturePermission.REPORTS,
        icon: ShieldAlert,
      },
    ],
  },
  {
    id: "invoices",
    title: "Invoice Management",
    tKey: "nav.invoiceManagement",
    icon: FileStack,
    items: [
      {
        id: 6.51,
        title: "Invoice List",
        tKey: "nav.invoiceList",
        link: "/invoices",
        permission: FeaturePermission.ORDER_INVOICE_FINANCE,
        icon: FileText,
      },
      
    ],
  },
  {
    id: "my-cash",
    title: "My Cash",
    tKey: "nav.myCash",
    icon: Wallet,
    permission: FeaturePermission.MY_CASH,
    items: [
      {
        id: 20.1,
        title: "Income",
        tKey: "nav.income",
        link: "/my-cash/income",
        permission: FeaturePermission.MY_CASH,
        icon: TrendingUp,
      },
      {
        id: 20.2,
        title: "Expense",
        tKey: "nav.expense",
        link: "/my-cash/expense",
        permission: FeaturePermission.MY_CASH,
        icon: TrendingDown,
      },
    ],
  },
  {
    id: "products",
    title: "Inventory Management",
    tKey: "nav.productManagement",
    icon: Package,
    items: [
      {
        id: 6,
        title: "Product",
        tKey: "nav.product",
        link: "/products",
        permission: FeaturePermission.PRODUCTS,
        icon: Box,
      },
      {
        id: 7,
        title: "Categories",
        tKey: "nav.categories",
        link: "/categories",
        permission: FeaturePermission.CATEGORY,
        icon: Tags,
      },
      {
        id: 7.5,
        title: "Inventory",
        tKey: "nav.inventory",
        link: "/inventory",
        permission: FeaturePermission.INVENTORY_MANAGEMENT,
        icon: Warehouse,
      },
      {
        id: 8,
        title: "Flash Sell",
        tKey: "nav.flashSell",
        link: "/flash-sell",
        permission: FeaturePermission.FLASH_SELL,
        icon: Zap,
      },
      {
        id: 7.9,
        title: "Product Sticker",
        tKey: "nav.productSticker",
        link: "/product-sticker",
        permission: FeaturePermission.PRODUCT_STICKER,
        icon: Barcode,
      },
    ],
  },
  {
    id: "customers",
    title: "Customer Management",
    tKey: "nav.customerManagement",
    icon: Users,
    items: [
      {
        id: 9,
        title: "Customers",
        tKey: "nav.customers",
        link: "/customers",
        permission: FeaturePermission.CUSTOMERS,
        icon: Contact,
      },
      {
        id: 9.5,
        title: "Reviews",
        tKey: "nav.reviews",
        link: "/reviews",
        permission: FeaturePermission.REVIEW,
        icon: Star,
      },
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    tKey: "nav.marketingPromotions",
    icon: Megaphone,
    items: [
      {
        id: 10,
        title: "Banners",
        tKey: "nav.banners",
        link: "/banners",
        permission: FeaturePermission.BANNER_MANAGEMENT,
        icon: Flag,
      },
      {
        id: 11,
        title: "Promocodes",
        tKey: "nav.promocodes",
        link: "/promocodes",
        permission: FeaturePermission.SETTINGS,
        icon: Ticket,
      },
      {
        id: 11.5,
        title: "Banners & Offers",
        tKey: "nav.bannersOffers",
        link: "/banners-offers",
        permission: FeaturePermission.BANNERS_OFFERS_MARKETING,
        icon: Megaphone,
      },
      {
        id: 11.6,
        title: "Top Products",
        tKey: "nav.topProducts",
        link: "/top-products",
        permission: FeaturePermission.SETTINGS,
        icon: LayoutDashboard,
      },
    ],
  },
  {
    id: "content",
    title: "Content & Policy",
    tKey: "nav.contentPolicy",
    icon: BookOpen,
    items: [
      {
        id: 12,
        title: "Privacy Policy",
        tKey: "nav.privacyPolicy",
        link: "/privacy-policy",
        permission: FeaturePermission.PRIVACY_POLICY_MANAGEMENT,
        icon: Shield,
      },
      {
        id: 13,
        title: "Terms & Conditions",
        tKey: "nav.termsConditions",
        link: "/terms-conditions",
        permission: FeaturePermission.TERMS_CONDITIONS_MANAGEMENT,
        icon: ScrollText,
      },
      {
        id: 14,
        title: "Refund Policy",
        tKey: "nav.refundPolicy",
        link: "/refund-policy",
        permission: FeaturePermission.REFUND_POLICY_MANAGEMENT,
        icon: Undo2,
      },
    ],
  },
  {
    id: "system",
    title: "Admin",
    tKey: "nav.system",
    icon: Lock,
    items: [
      {
        id: 15,
        title: "Manage Users",
        tKey: "nav.manageUsers",
        link: "/manage-users",
        permission: FeaturePermission.STAFF,
        icon: UserCog,
        children: [
          {
            title: "All Users",
            tKey: "nav.allUsers",
            link: "/manage-users?tab=all-users",
            permission: FeaturePermission.STAFF,
            icon: Users,
          },
          {
            title: "Active",
            tKey: "nav.activeUsers",
            link: "/manage-users?tab=active",
            permission: FeaturePermission.STAFF,
            icon: CheckCircle2,
          },
          {
            title: "Inactive",
            tKey: "nav.inactiveUsers",
            link: "/manage-users?tab=inactive",
            permission: FeaturePermission.STAFF,
            icon: XCircle,
          },
        ],
      },
      {
        id: 15.5,
        title: "Resellers",
        tKey: "nav.resellers",
        link: "/resellers",
        permission: FeaturePermission.RESELLER_MANAGEMENT,
        icon: Package,
      },
      {
        id: 16,
        title: "Settings",
        tKey: "nav.settings",
        link: "/settings",
        permission: FeaturePermission.SETTINGS,
        icon: Settings2,
        children: [
          {
            title: "General",
            tKey: "nav.settingsGeneral",
            link: "/settings?tab=general",
            permission: FeaturePermission.SETTINGS,
            icon: Settings,
          },
          {
            title: "Preferences",
            tKey: "nav.settingsPreferences",
            link: "/settings?tab=preferences",
            permission: FeaturePermission.SETTINGS,
            icon: SlidersHorizontal,
          },
          {
            title: "Account",
            tKey: "nav.settingsAccount",
            link: "/settings?tab=account",
            permission: FeaturePermission.SETTINGS,
            icon: User,
          },
          {
            title: "Billings",
            tKey: "nav.settingsBillings",
            link: "/settings?tab=billings",
            permission: FeaturePermission.SETTINGS,
            icon: CreditCard,
          },
          {
            title: "Notifications",
            tKey: "nav.settingsNotifications",
            link: "/settings?tab=notifications",
            permission: FeaturePermission.SETTINGS,
            icon: Bell,
          },
        ],
      },

      {
        id: 17,
        title: "Upgrade Plan",
        tKey: "nav.upgradePlan",
        link: "/upgrade-plan",
        permission: FeaturePermission.SETTINGS,
        icon: Crown,
      },
      {
        id: 18,
        title: "Help",
        tKey: "nav.help",
        link: "/help",
        permission: FeaturePermission.HELP,
        icon: LifeBuoy,
      },
    ],
  },
  // {
  //   id: "integrations",
  //   title: "Reports",
  //   tKey: "nav.integrations",
  //   icon: BarChart,
  //   items: [
  //     {
  //       id: 19,
  //       title: "Connected Apps",
  //       tKey: "nav.connectedApps",
  //       link: "/connected-apps",
  //       permission: FeaturePermission.REPORTS,
  //       icon: LayoutGrid,
  //     },
  //   ],
  // },
];

// Flattened navLinks for backward compatibility
export const navLinks = navSections.flatMap((section) => section.items);

export const DROPDOWN_NAV_ITEMS = [
  {
    title: "Personal Information",
    tKey: "nav.personalInformation",
    link: "/settings/personal-information",
    icon: User2,
  },
  {
    title: "Settings",
    tKey: "nav.settings",
    link: "/settings/account-security",
    icon: Settings,
  },
];
